# Generated by Django 5.2.5 on 2026-02-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milkorder',
            name='milk_type',
        ),
        migrations.AddField(
            model_name='milkorder',
            name='brand',
            field=models.CharField(blank=True, choices=[('AMUL', 'Amul'), ('VIKAS', 'Vikas'), ('SARASWATI', 'Saraswati'), ('AMAR', 'Amar')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='milkorder',
            name='pack_size',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='milkorder',
            name='packets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='milkorder',
            name='product_type',
            field=models.CharField(choices=[('MILK', 'Milk'), ('GHEE', 'Ghee'), ('PANEER', 'Paneer'), ('CURD', 'Curd'), ('BUTTER', 'Butter')], default='MILK', max_length=20),
        ),
        migrations.AddField(
            model_name='milkorder',
            name='total_liters',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='milkorder',
            name='unit',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='milkorder',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='milkorder',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='milkorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
