# Generated by Django 5.2.5 on 2026-02-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_milkorder_milk_type_milkorder_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkorder',
            name='milk_type',
            field=models.CharField(blank=True, choices=[('COW', 'Cow Milk'), ('BUFFALO', 'Buffalo Milk')], max_length=10, null=True),
        ),
    ]
