# Generated by Django 5.2.5 on 2026-02-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_milkorder_milk_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milktransaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='milktransaction',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid')], default='UNPAID', max_length=10),
        ),
    ]
