# Generated by Django 5.2.5 on 2026-02-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_milktransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milktransaction',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid')], max_length=10),
        ),
    ]
