# Generated by Django 5.2.5 on 2026-02-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_milktransaction_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milktransaction',
            name='liters',
        ),
        migrations.AddField(
            model_name='milktransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='milktransaction',
            name='unit',
            field=models.CharField(choices=[('L', 'L'), ('KG', 'KG'), ('PCS', 'PCS')], default='L', max_length=10),
        ),
        migrations.AlterField(
            model_name='milktransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='milktransaction',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid')], default='UNPAID', max_length=10),
        ),
        migrations.AlterField(
            model_name='milktransaction',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
