# Generated by Django 5.2.5 on 2026-02-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_milktransaction_liters_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milktransaction',
            old_name='quantity',
            new_name='qty',
        ),
        migrations.AddField(
            model_name='milktransaction',
            name='product_type',
            field=models.CharField(choices=[('MILK', 'Milk'), ('GHEE', 'Ghee'), ('PANEER', 'Paneer'), ('CURD', 'Curd'), ('BUTTER', 'Butter')], default='MILK', max_length=20),
        ),
        migrations.AlterField(
            model_name='milktransaction',
            name='unit',
            field=models.CharField(choices=[('L', 'Liters'), ('KG', 'Kilogram'), ('PCS', 'Pieces')], default='L', max_length=10),
        ),
    ]
