# Generated by Django 5.2.5 on 2026-02-10 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customer_owner_milkorder_owner_milktransaction_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='milkorder',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='milktransaction',
            name='owner',
        ),
    ]
