# Generated by Django 5.2.5 on 2026-02-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_customer_owner_remove_milkorder_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='login_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='login_phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='milkorder',
            name='placed_by',
            field=models.CharField(choices=[('SHOPKEEPER', 'Shopkeeper'), ('CUSTOMER', 'Customer')], default='SHOPKEEPER', max_length=20),
        ),
        migrations.AddField(
            model_name='milkorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20),
        ),
    ]
