# Generated by Django 5.2.5 on 2026-02-11 15:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_customer_login_password_customer_login_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkorder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
