# Generated by Django 5.2.5 on 2026-02-12 19:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_milkorder_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkorder',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
